### ISSUE TITLE
Validation of fields and images

### ISSUE THREAD

**Issue by abigail830** [abigail830/blindbox#17]
@sohaha 图片格式大小之类要求，可以记录在这里，和那些名字和描述之类的field长度

**Comment by sohaha** [comment]
名字长度这些很多无法给出: 比如 角色名称 中文是 5 位 英文是 7 位 那么给你 5 位还是 7 位 

目前前端对过长的自行加上省略号 
![image](https://user-images.githubusercontent.com/18098083/77874279-0e076480-727f-11ea-9400-88f475123c37.png)

**Comment by abigail830** [comment]
@sohaha 那还有各种图片的尺寸或者比例要求哦
