### ISSUE TITLE
卡券方案待定

### ISSUE THREAD

**Issue by cjr100week** [abigail830/blindbox#2]
继续考虑关于卡券的问题：
a）如果使用小程序内打开卡包，枚举卡券并使用的方式
注意文档中似乎更针对，在小程序内开会员卡的场景。相对来说对卡券支持似乎比较弱（尤其是在另一个公众号中派发的）
代码方面我目前调研似乎是，必须先知道卡券id(这个卡券id应该是在卡券制作的时候固定了的，如果使用的话可以建议运营期间只修改不增减
应该就可以做到相对优惠券确定。
 
从而，进入支付的流程时候，根据预配的卡券id，获取优惠券信息；
然后在支付的时候，根据优惠券计算支付金额
支付成功后，核销卡券。
 
但这个做法我疑虑几个问题：
1. 一旦新增优惠券，需要修改前端代码，不够灵活；
2. 对重复领券比较难把控（由于id固定，似乎就只可以开放每人可以领取多券，加上卡券转赠，有可能出现计划外派发失控问题）
 
 
B）考虑是否用针对积分，进行另一种卡券营销：派发的卡券一律兑换成系统内积分。
具体操作是：
运营方按活动制券，所有卡券都落实到奖励用户积分。
用户换取积分的办法是，点击立即使用。点击后跳转小程序页面，在页面上兑换积分。兑换成功后可以马上使用。
 
代码实现上，抛个砖头考虑这个方案：
在卡券自定义入口中，配置专门的跳转入口：
如
index/redeem?promotion=xxx&expired=xxxx&redeem=xxx&sign=xxxxx
 
Sign我们可以是内部算法，随便弄个加个子串后sha256之类看不懂的就差不多；后台可以提供生成；
（运营每次添加卡券，手动定义promotion，expired，redeem，然后去后台获取小程序入口，再配置到跳转小程序中）

 
 
 
前端收到后，只要校验正确，就根据redeem给与积分，并且promotion记录（下次再进来，查找如果promotion用过了就不加了）。
 
等于开放加分的灵活性给未来运营使用。
 
影浅觉得觉得可行不？
如果某个方案是不可行的，直接去除；如果两个方案都可行，看丹丹最终考虑哪个更适合于用户实际落实推广。

**Comment by sohaha** [comment]
a). 
1. 需要通过接口获取卡券的,不存在前端需要改代码
2. 无解,因为微信卡券不是为了在这种场景下使用的

b). 
目前最优的就只有这种可以由我们自行把控的方式,
哪怕不和积分挂钩,最终也可以实现一套程序内部使用的卡券系统(手动狗头)

@cjr100week
