### ISSUE TITLE
产品的接口有些困惑

### ISSUE THREAD

**Issue by sohaha** [abigail830/blindbox#22]
![image](https://user-images.githubusercontent.com/18098083/77871426-acdb9300-7276-11ea-8bb8-8633c091adca.png)

![image](https://user-images.githubusercontent.com/18098083/77871447-bd8c0900-7276-11ea-9d1c-70a633fb23e0.png)

在名人堂这个页面需要三个数据

1 角色列表的数据  /wx/products/roles

2 角色拥有的系列数据 `/wx/products/${roleId}/series`

3 系列内拥有的产品数据 `/wx/products/series/${seriesId}`  **这个不应该是一个列表(数组)数据吗?**

![image](https://user-images.githubusercontent.com/18098083/77872681-3e98cf80-727a-11ea-80a2-e2d44e1f058d.png)

还有说我用错接口了

**Comment by abigail830** [comment]
- /wx/products/series/${seriesId}  说的应该是那个选定系列的信息，现在应该是没有包括系列内的产品信息，方法一是在这里也直接附上该系列包含的所有产品
- 另一个方式就是另外一个endpoint 比如/wx/products/series/${seriesId} /products，去获取这个系列里面的所有产品

@sohaha 对上面两种方式有没preference？

**Comment by sohaha** [comment]
@abigail830 第二种吧, 防止一个接口返回的数据过大

**Comment by bryan-cheung** [comment]
/wx/products/series/${seriesId} 返回产品系列的信息和产品的数量
前端需要一个返回产品（包括产品信息）列表的接口？

**Comment by abigail830** [comment]
@bryan-cheung 
 yes, such as /wx/products/series/${seriesId} /products
and need to include price

**Comment by sohaha** [comment]
@bryan-cheung 我不知道他有没激活了该产品 ,所以需要你告诉我
