### ISSUE TITLE
无效测试数据

### ISSUE THREAD

**Issue by lyf199800** [abigail830/blindbox#28]
![image](https://user-images.githubusercontent.com/43807744/80193425-5bdb7680-864b-11ea-9788-d5ef674b0cea.png)
![image](https://user-images.githubusercontent.com/43807744/80193436-6269ee00-864b-11ea-8ed7-e3cb58af07e3.png)

建议手动清除 
@abigail830

**Comment by abigail830** [comment]
因为切换了PROD DB，这个就先不管了～后续继续在PROD观察有没类似问题吧
