### ISSUE TITLE
第二轮点击卡片无反应

### ISSUE THREAD

**Issue by lyf199800** [abigail830/blindbox#29]
初次进去有七个积分，点击抽盒，点击三种券，有反应，点击付款，取消；换盒，点击三种券，无反应，查看我的积分，仍是七个。
猜测的原因:第一轮我使用了三个券，但付款的时候取消了，此时积分已经用了，只是前端未更新，所以第二次轮点击的时候没有足够的积分兑换券，故没有反应。
建议解决办法：积分数实时更新，积分不够时设置提示
@sohaha @abigail830

**Comment by abigail830** [comment]
每次用完基本，后台应该是已经返回了最新的积分情况，前台应该是可以拦截后续不够积分的点击的
所以先assign给@sohaha

**Comment by lyf199800** [comment]
再次测试没有问题，暂时关闭
