### ISSUE TITLE
订单显示出错

### ISSUE THREAD

**Issue by lyf199800** [abigail830/blindbox#30]
未申请发货的订单，申请发货后取消付款，订单消失
@sohaha @abigail830

**Comment by lyf199800** [comment]
并且在申请发货界面 点击发货无反应

**Comment by lyf199800** [comment]
未申请发货的订单，申请发货后取消，直接变成未发货了(但实际未付运费) @abigail830

**Comment by abigail830** [comment]
should be fixed.
