### ISSUE TITLE
删除地址出错

### ISSUE THREAD

**Issue by lyf199800** [abigail830/blindbox#31]
![image](https://user-images.githubusercontent.com/43807744/80195996-4a946900-864f-11ea-8287-dfdcf6fa978b.png)
@sohaha

**Comment by abigail830** [comment]
sql问题已修复，但现在删除之后会停留在原来页面没有任何反映，如果再删除就会报错，如果退出来就能看到其实已经删除了
 @sohaha 需要前端在删除成功后跳转到列表页
