### ISSUE TITLE
 订单时间差了一个小时？

### ISSUE THREAD

**Issue by cjr100week** [abigail830/blindbox#36]
![image](https://user-images.githubusercontent.com/37078626/80302468-d2f44480-87dc-11ea-90d2-8e6eee2b3447.png)
我实际支付时间应该是16：40左右，显示的是17：40；
是不是服务器时钟配置时区之类需要修正一下呢？

**Comment by abigail830** [comment]
@cjr100week 后台呢？比如活动时间、订单时间这些，有没同样问题？

**Comment by abigail830** [comment]
fixed

**Comment by lyf199800** [comment]
fixed
