### ISSUE TITLE
选择三个产品，点击送货后，没有反应

### ISSUE THREAD

**Issue by cjr100week** [abigail830/blindbox#37]
![image](https://user-images.githubusercontent.com/37078626/80302553-38e0cc00-87dd-11ea-843d-362884f3fa81.png)
![image](https://user-images.githubusercontent.com/37078626/80302557-3da58000-87dd-11ea-9929-8765a344f415.png)
![image](https://user-images.githubusercontent.com/37078626/80302565-4c8c3280-87dd-11ea-9c70-e5f6e849807b.png)
![image](https://user-images.githubusercontent.com/37078626/80302570-544bd700-87dd-11ea-9a94-7ce710435f15.png)

看起来已经发送过 后台请求。但没有转入 待发货 状态。并且下下次还可以在未申请中找到这三个产品。

**Comment by abigail830** [comment]
fixed @cjr100week

**Comment by lyf199800** [comment]
fixed
