### ISSUE TITLE
点了预约活动  没有预约成功的一个提示显示 （导致没有预约上，也没有收到提醒）

### ISSUE THREAD

**Issue by cjr100week** [abigail830/blindbox#40]
丹丹建议是给预约状态一个提示
丹丹看给个更明确的截图信息，然后分配制作。

**Comment by abigail830** [comment]
@cjr100week 
现在后台有一个校验，如果活动已经开始了，用户就不能够再预约，如果前台还发来预约，后台会返回exception提示给前台（有可能前台没有把异常显示出来），在这种场景下，就会出现他无论怎么点都没有反应。看是否需要类似的校验

**Comment by youdandan** [comment]
用户点击“预约活动“后，按钮的文字变成“预约成功“就可以了。

**Comment by youdandan** [comment]
用户点击“预约活动“后，按钮的文字变成“预约成功“，按钮颜色变成灰色，就可以了。

**Comment by lyf199800** [comment]
当用户预约成功退出活动再次进入时，按钮又恢复原样了。能否一直保持“预约成功”的字样呢，或者丹丹姐看下是否需要保持？ @youdandan @abigail830

**Comment by abigail830** [comment]
![image](https://user-images.githubusercontent.com/19251334/82750154-c87b9980-9de0-11ea-8e7b-eeda47c1099d.png)
存在API可以判断该用户是否订阅了活动 @sohaha

**Comment by youdandan** [comment]
这种情况应该不会订阅不成功？如果活动过期，按钮灰色就可以了。

**Comment by lyf199800** [comment]
> 当用户预约成功退出活动再次进入时，按钮又恢复原样了。能否一直保持“预约成功”的字样呢，或者丹丹姐看下是否需要保持？ @youdandan @abigail830

此功能已添加，预约成功退出活动后再次进入活动，按钮为灰色并且显示预约成功
![image](https://user-images.githubusercontent.com/43807744/82787452-00461800-9e99-11ea-8583-3dae76b26c6b.png)

**Comment by lyf199800** [comment]
新的疑点，活动过期后点击“活动开始提醒我”没有任何反应，既不提示错误信息比如活动过期，也不显示预约成功，按钮也不变灰 @sohaha @abigail830

**Comment by lyf199800** [comment]
> 新的疑点，活动过期后点击“活动开始提醒我”没有任何反应，既不提示错误信息比如活动过期，也不显示预约成功，按钮也不变灰 @sohaha @abigail830

fixed,过期活动显示活动已过期，按钮变灰
![image](https://user-images.githubusercontent.com/43807744/82798141-b82ff100-9eaa-11ea-8905-a9ac0f68612a.png)
