### ISSUE TITLE
积分没有变动

### ISSUE THREAD

**Issue by cjr100week** [abigail830/blindbox#41]
购买商品后没发现积分有所变动
是不是代码没关联，还是因为我们购买0.01所以没有正确触发呢？请考虑修复或者给个测试方式（比如关联测试的0.01购买到正常的积分规则上？）

**Comment by abigail830** [comment]
@cjr100week 原来的需求里面就没有给说购买需要加多少积分啊

**Comment by lyf199800** [comment]
fixed，每次购买增加了20积分
