### ISSUE TITLE
海报可否提供后台修改

### ISSUE THREAD

**Issue by cjr100week** [abigail830/blindbox#45]
在后台上提供海报修改让用户后期修改海报可以么

**Comment by abigail830** [comment]
现在的海报是什么样的？是统一一个样子？还是跟产品/角色/用户之类的变化？

**Comment by sohaha** [comment]
可以呀，但是需要后端来计算素材的位置喔

**Comment by cjr100week** [comment]
能否后端传下来底图，然后前端再处理呢？（或者开始的时候去api请求更新，先缓存一下海报图）；
另外海报应该添加二维码的话，有无设计提示？（比如他们应该保留哪个位置，我们不会去用素材覆盖的，去放二维码比较合适？）

**Comment by lyf199800** [comment]
fixed,可修改底图
