### ISSUE TITLE
订单号规则，尽量用数字不用guid这种；

### ISSUE THREAD

**Issue by cjr100week** [abigail830/blindbox#47]
订单号规则，尽量用数字不用guid这种；

 状态栏目有看翻译一下？

PAY_TRANSPORT_SUCCESS 
PAY_PRODUCT_SUCCESS
DELIVERED
PAY_PRODUCT_EXPIRY

![image](https://user-images.githubusercontent.com/37078626/81637743-b8ab9f00-9449-11ea-9317-c7660c76884f.png)

**Comment by abigail830** [comment]
@cjr100week 
影响有多大？现在是直接用的腾信支付的orderId，所以是按照他的要求必须酱紫，如果要改的话表结构也是需要改的

**Comment by cjr100week** [comment]
明白。那orderId就不改吧：）
状态栏还是将就着小白水平对应翻译一下呗~：）

**Comment by abigail830** [comment]
low priority, close firse

**Comment by abigail830** [comment]
Only for update the mapping from English and Chinese

**Comment by abigail830** [comment]
done. will release later today
