### ISSUE TITLE
活动预约后发送的模版信息，活动规则，活动奖励还是需要后台提供独立配置去修改？

### ISSUE THREAD

**Issue by cjr100week** [abigail830/blindbox#50]
![image](https://user-images.githubusercontent.com/37078626/81713759-dbb96b80-94a8-11ea-8d6d-7aa7810b53f1.png)

这几个字段，对应的是需要给发送模版信息时填入字段的，用现在的富文本填充似乎不合适。
是否可以分开对应字段给配置？

反而描述的话，他们倾向用长图直接描述，一张活动主图就够了（但最好给出分辨率建议，至少是宽度建议以及文件尺寸限制建议（少于多少M才不会导致上传413错误？））

**Comment by cjr100week** [comment]
![image](https://user-images.githubusercontent.com/37078626/81714077-3fdc2f80-94a9-11ea-9db5-782e7f59c49b.png)

需要配置的字段主要是这几个。
时间的话看是不是也要用到订阅信息后发送的时间节点上。

**Comment by abigail830** [comment]
0.67

**Comment by lyf199800** [comment]
fixed,模板消息可自定义编辑
