### ISSUE TITLE
名人堂与名人堂海报如果没抽中过的话，能否默认灰色

### ISSUE THREAD

**Issue by cjr100week** [abigail830/blindbox#51]
![image](https://user-images.githubusercontent.com/37078626/81714847-196ac400-94aa-11ea-9d36-429ef7c6aa6d.png)

![image](https://user-images.githubusercontent.com/37078626/81714760-ff30e600-94a9-11ea-803c-4a1b973abe2a.png)

**Comment by sohaha** [comment]
前端不知道有没抽过的, 没抽的接口应该返回灰色的图片

**Comment by abigail830** [comment]
@sohaha 意思是有一个接口返回对应这个openId用户的所有抽过（就是买了）的产品列表？

**Comment by abigail830** [comment]
@cjr100week 这个和#36是否同一回事？

**Comment by sohaha** [comment]
@abigail830  如果没有什么别的需求, 对前端最友好和前端性能高效的就是返回产品信息列表的接口直接加个字段 该产品是否抽中过, 

如果后端业务不好处理,那么就只能前端拿到两组数据然后再去过滤匹配,主要这样对前端而已两个接口产生了强关联.

不过后端那么怎么方便怎么来吧

**Comment by lyf199800** [comment]
fixed,初始为灰，抽中后为白
