### ISSUE TITLE
角色和系列关系改为多对多

### ISSUE THREAD

**Issue by abigail830** [abigail830/blindbox#54]
high priority
针对不同角色可能会有相同的系列，模型、数据库和相关api都需要改动，尽量接口保持前端兼容

- [x] remove useless field from role table and admin page
- [x] Series table v2
- [x] role & series mapping
- [x] backend role maint page
- [x] backend series maint page for maint mapping
- [x] wx api update for all related

**Comment by cjr100week** [comment]
请远烽着重验证：
 多个角色，有同一系列产品。
检查抽盒行为，产品系列过滤筛选页面，后端发货界面，后端库存界面，名人堂，以及其它可能相关流程是否完全正确。

**Comment by lyf199800** [comment]
fixed
