### ISSUE TITLE
系列图鉴显示的产品数应为该系列的产品数

### ISSUE THREAD

**Issue by lyf199800** [abigail830/blindbox#63]
目前显示的好像是"显示盲盒总数"的数量？
![image](https://user-images.githubusercontent.com/43807744/83642334-47db4b00-a5e1-11ea-9256-6582ec51eed4.png)
![image](https://user-images.githubusercontent.com/43807744/83642417-63465600-a5e1-11ea-8178-aa1e04741aaf.png)

**Comment by lyf199800** [comment]
@sohaha @abigail830

**Comment by sohaha** [comment]
和重叠同一个bug
